-- 在 Supabase Dashboard > SQL Editor 中执行本文件。
-- 该表独立于文学阅读池的 reading_records，避免两套阅读数据互相污染。

create table if not exists public.detective_reading_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_id text not null,
  country text not null,
  author_name text not null,
  work_title text not null,
  status text not null check (status in ('want','reading','done','paused')),
  progress integer not null default 0 check (progress between 0 and 100),
  rating numeric(2,1) check (rating is null or (rating >= 1 and rating <= 5)),
  started_at date,
  finished_at date,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, work_id)
);

create index if not exists detective_records_user_status_idx
  on public.detective_reading_records (user_id, status);

alter table public.detective_reading_records enable row level security;

drop policy if exists "Users can read own detective records" on public.detective_reading_records;
create policy "Users can read own detective records"
  on public.detective_reading_records for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own detective records" on public.detective_reading_records;
create policy "Users can insert own detective records"
  on public.detective_reading_records for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own detective records" on public.detective_reading_records;
create policy "Users can update own detective records"
  on public.detective_reading_records for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own detective records" on public.detective_reading_records;
create policy "Users can delete own detective records"
  on public.detective_reading_records for delete
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.detective_reading_records to authenticated;
grant usage, select on sequence public.detective_reading_records_id_seq to authenticated;
