const SUPABASE_URL='https://qlumnvsjjgawisnjbvxf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_ivUKkA15AANQVXH_SwHP0Q_SVcSlvAC';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const authors=window.detectiveAuthors||[],$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const works=[];authors.forEach(a=>a.works.forEach((w,i)=>works.push({...w,id:encodeURIComponent(`${a.country}|${a.name}|${w.title}`),country:a.country,author:a.name,tradition:a.tradition,index:i})));
let records=JSON.parse(localStorage.getItem('detectiveReadingRecords')||'{}'),user=null,selectedCountry='日本',selectedAuthor='京极夏彦',shelfFilter='all';
const statusText={want:'想读',reading:'在读',done:'已读',paused:'暂停'};
function saveLocal(){localStorage.setItem('detectiveReadingRecords',JSON.stringify(records))}
function recordOf(id){return records[id]||{status:'',progress:0,rating:null,started_at:'',finished_at:'',notes:''}}
function setBanner(text,type=''){const x=$('#syncBanner');x.textContent=text;x.className='sync-banner'+(type?' '+type:'')}
function showPage(name){$$('.page').forEach(x=>x.classList.toggle('hidden',x.id!==name+'Page'));$$('.page').forEach(x=>x.classList.toggle('active',x.id===name+'Page'));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='archive')renderArchive();if(name==='timeline')renderTimeline();if(name==='shelf')renderShelf();scrollTo({top:0,behavior:'smooth'})}
function renderDashboard(){
 $('#statWorks').textContent=works.length;$('#statAuthors').textContent=authors.length;$('#statReading').textContent=Object.values(records).filter(x=>x.status==='reading').length;$('#statDone').textContent=Object.values(records).filter(x=>x.status==='done').length;
 const k=authors.find(x=>x.name==='京极夏彦');$('#kyogokuFeature').innerHTML=k.works.slice(0,6).map((w,i)=>{const x=works.find(v=>v.author===k.name&&v.title===w.title),r=recordOf(x.id);return `<article class="feature"><small>KYOGOKUDO / ${String(i+1).padStart(2,'0')}</small><h3>《${w.title}》</h3><p>百鬼夜行系列 · ${r.status?statusText[r.status]:'未加入案卷'}</p><button class="record-btn ${r.status?'has':''}" data-record="${x.id}">${r.status?'编辑':'＋ 案卷'}</button></article>`}).join('')
}
function countries(){return [...new Set(authors.map(x=>x.country))]}
function renderArchive(query=$('#search').value.trim().toLowerCase()){
 const filteredAuthors=authors.filter(a=>(a.country+a.name+a.tradition+a.works.map(w=>w.title).join('')).toLowerCase().includes(query));
 const available=new Set(filteredAuthors.map(a=>a.country));if(query&&!available.has(selectedCountry))selectedCountry=[...available][0]||'';
 $('#countryList').innerHTML=countries().filter(c=>!query||available.has(c)).map(c=>{const aa=authors.filter(a=>a.country===c),count=aa.reduce((n,a)=>n+a.works.length,0);return `<button class="country-item ${c===selectedCountry?'active':''}" data-country="${c}"><b>${c}</b><span>${aa.length} 位作者 · ${count} 部作品</span></button>`}).join('');
 let list=filteredAuthors.filter(a=>a.country===selectedCountry);if(!list.length&&filteredAuthors.length){selectedCountry=filteredAuthors[0].country;list=filteredAuthors.filter(a=>a.country===selectedCountry)}if(!list.some(a=>a.name===selectedAuthor))selectedAuthor=list[0]?.name||'';
 $('#authorList').innerHTML=list.map(a=>{const done=a.works.filter(w=>recordOf(works.find(x=>x.author===a.name&&x.title===w.title).id).status==='done').length;return `<button class="author-item ${a.name===selectedAuthor?'active':''}" data-author="${a.name}"><b>${a.name}</b><span>${a.tradition} · ${done}/${a.works.length} 已读</span></button>`}).join('');renderDetail()
}
function renderDetail(){const a=authors.find(x=>x.country===selectedCountry&&x.name===selectedAuthor);if(!a){$('#detail').innerHTML='<div class="empty">没有匹配的作者档案</div>';return}$('#detail').innerHTML=`<header class="author-hero"><p class="eyebrow">${a.country} / ${a.tradition}</p><h2>${a.name}</h2><p>${a.works.length} 部作品收录。点击“案卷”记录状态、进度、评分和笔记。</p></header><div class="work-list">${a.works.map((w,i)=>{const x=works.find(v=>v.author===a.name&&v.title===w.title),r=recordOf(x.id);return `<article class="work-card"><div class="meta"><span>FILE ${String(i+1).padStart(3,'0')}</span><span class="tag">${a.tradition}</span>${r.status?`<span class="tag">${statusText[r.status]} ${r.progress||0}%</span>`:''}</div><h3>《${w.title}》</h3><p>${a.name}作品档案。正式版可继续补充首版年份、系列顺序、中文版本与无剧透导读。</p><button class="record-btn ${r.status?'has':''}" data-record="${x.id}">${r.status?'编辑案卷':'＋ 案卷'}</button></article>`}).join('')}</div>`}
const eras=[
 ['1841—1886','侦探的诞生','坡与柯林斯确立了侦探、线索和理性复原秩序的基本模型。'],
 ['1887—1919','名侦探神话','福尔摩斯使侦探成为连续系列人物，读者共同体和类型规则逐渐稳定。'],
 ['1920—1945','黄金时代与硬汉派','英国把犯罪变成公平的智力游戏，美国则将它重新放回资本、街道和暴力。'],
 ['1946—1979','社会派与警察程序','战后推理开始追问制度、阶级和创伤，破案不再等同于秩序恢复。'],
 ['1980—1999','新本格、心理与历史','岛田庄司、绫辻行人复兴诡计，埃科与海史密斯等人不断扩张类型边界。'],
 ['2000—2019','全球犯罪叙事','北欧犯罪、家庭悬疑、中国社会派和日本多种本格分支形成全球并行谱系。'],
 ['2020—NOW','混合类型时代','舒适推理、文档推理、幻想推理和播客叙事使侦探小说进入新的媒介环境。']];
function renderTimeline(){ $('#timelineList').innerHTML=eras.map(e=>`<article class="era"><time>${e[0]}</time><div><h2>${e[1]}</h2><p>${e[2]}</p></div></article>`).join('') }
function renderShelf(){let rows=works.filter(w=>records[w.id]?.status&&(shelfFilter==='all'||records[w.id].status===shelfFilter));$('#shelfInsight').textContent=`共记录 ${Object.keys(records).length} 部作品，其中已读 ${Object.values(records).filter(x=>x.status==='done').length} 部。`;$('#shelfList').innerHTML=rows.length?rows.map(w=>{const r=recordOf(w.id);return `<article class="shelf-card" data-record="${w.id}"><div class="meta"><span>${w.country}</span><span>${statusText[r.status]}</span>${r.rating?`<span>${r.rating}/5</span>`:''}</div><h3>《${w.title}》</h3><p>${w.author} · ${w.tradition}</p><div class="progress"><i style="width:${r.progress||0}%"></i></div></article>`}).join(''):'<div class="empty">当前分类还没有阅读记录。</div>'}
function openRecord(id){const w=works.find(x=>x.id===id),r=recordOf(id);if(!w)return;$('#recordWorkId').value=id;$('#recordTitle').textContent='《'+w.title+'》';$('#recordMeta').textContent=`${w.author} · ${w.country} · ${w.tradition}`;$('#recordStatus').value=r.status||'';$('#recordProgress').value=r.progress||0;$('#recordRating').value=r.rating??'';$('#recordStarted').value=r.started_at||'';$('#recordFinished').value=r.finished_at||'';$('#recordNotes').value=r.notes||'';$('#deleteRecord').classList.toggle('hidden',!records[id]);$('#recordDialog').showModal()}
async function persistRecord(id,payload){if(!payload.status)delete records[id];else records[id]=payload;saveLocal();if(!user)return;const w=works.find(x=>x.id===id);if(!payload.status){const {error}=await db.from('detective_reading_records').delete().eq('user_id',user.id).eq('work_id',id);if(error)throw error}else{const {error}=await db.from('detective_reading_records').upsert({user_id:user.id,work_id:id,country:w.country,author_name:w.author,work_title:w.title,status:payload.status,progress:payload.progress,rating:payload.rating,started_at:payload.started_at||null,finished_at:payload.finished_at||null,notes:payload.notes,updated_at:new Date().toISOString()},{onConflict:'user_id,work_id'});if(error)throw error}}
async function loadCloud(){const {data,error}=await db.from('detective_reading_records').select('*');if(error)throw error;const cloud={};(data||[]).forEach(r=>cloud[r.work_id]={status:r.status,progress:r.progress||0,rating:r.rating,started_at:r.started_at||'',finished_at:r.finished_at||'',notes:r.notes||''});const missing=Object.entries(records).filter(([id])=>!cloud[id]).map(([id,r])=>{const w=works.find(x=>x.id===id);return w?{user_id:user.id,work_id:id,country:w.country,author_name:w.author,work_title:w.title,status:r.status,progress:r.progress||0,rating:r.rating||null,started_at:r.started_at||null,finished_at:r.finished_at||null,notes:r.notes||'',updated_at:new Date().toISOString()}:null}).filter(Boolean);if(missing.length){const {error:e}=await db.from('detective_reading_records').upsert(missing,{onConflict:'user_id,work_id'});if(e)throw e}records={...records,...cloud};saveLocal();setBanner(`已登录 ${user.email}，侦探阅读记录已同步。`,'ok');renderAll()}
function renderAll(){renderDashboard();renderArchive();renderShelf()}
$$('.tab').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>showPage(b.dataset.open));$('#countryList').onclick=e=>{const b=e.target.closest('[data-country]');if(b){selectedCountry=b.dataset.country;selectedAuthor=authors.find(a=>a.country===selectedCountry)?.name||'';renderArchive()}};$('#authorList').onclick=e=>{const b=e.target.closest('[data-author]');if(b){selectedAuthor=b.dataset.author;renderArchive()}};document.addEventListener('click',e=>{const b=e.target.closest('[data-record]');if(b)openRecord(b.dataset.record)});$('#search').oninput=e=>{showPage('archive');renderArchive(e.target.value.trim().toLowerCase())};$$('[data-shelf]').forEach(b=>b.onclick=()=>{shelfFilter=b.dataset.shelf;$$('[data-shelf]').forEach(x=>x.classList.toggle('active',x===b));renderShelf()});
$('#recordForm').onsubmit=async e=>{e.preventDefault();const id=$('#recordWorkId').value,p={status:$('#recordStatus').value,progress:Math.max(0,Math.min(100,Number($('#recordProgress').value)||0)),rating:$('#recordRating').value?Number($('#recordRating').value):null,started_at:$('#recordStarted').value,finished_at:$('#recordFinished').value,notes:$('#recordNotes').value.trim()};try{await persistRecord(id,p);$('#recordDialog').close();renderAll()}catch(err){$('#recordMessage').textContent='保存失败：'+err.message}};$('#deleteRecord').onclick=async()=>{try{await persistRecord($('#recordWorkId').value,{status:''});$('#recordDialog').close();renderAll()}catch(err){$('#recordMessage').textContent='删除失败：'+err.message}};$('#closeRecord').onclick=()=>$('#recordDialog').close();
$('#loginButton').onclick=()=>$('#loginDialog').showModal();$('#closeLoginDialog').onclick=()=>$('#loginDialog').close();$('#loginForm').onsubmit=async e=>{e.preventDefault();const email=$('#loginEmail').value.trim(),redirectTo=location.origin+location.pathname;const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});$('#loginMessage').textContent=error?'发送失败：'+error.message:'登录链接已发送，请检查邮箱。'};$('#logoutButton').onclick=()=>db.auth.signOut();
db.auth.onAuthStateChange((event,session)=>setTimeout(async()=>{user=session?.user||null;$('#loginButton').classList.toggle('hidden',!!user);$('#userPanel').classList.toggle('hidden',!user);$('#userEmail').textContent=user?.email||'';if(user){try{await loadCloud()}catch(err){setBanner('云端同步失败：'+err.message,'error')}}else{setBanner('访客模式：阅读记录保存在当前浏览器。登录后可同步到 Supabase。');renderAll()}},0));
renderTimeline();renderAll();