const te=new TextEncoder(),td=new TextDecoder();
export default{async fetch(req,env){const u=new URL(req.url),o=req.headers.get('Origin')||'';if(req.method==='OPTIONS')return cors(new Response(null,{status:204}),o,env);try{let r;if(u.pathname==='/auth/login')r=await login(u,env);else if(u.pathname==='/auth/callback')r=await callback(u,env);else if(u.pathname==='/auth/status')r=await status(req,env);else if(u.pathname==='/publish'&&req.method==='POST')r=await publish(req,env);else r=j({error:'Not found'},404);return cors(r,o,env)}catch(e){return cors(j({error:e.message||'Unexpected error'},500),o,env)}}};
function cors(r,o,e){const h=new Headers(r.headers);if(o===e.SITE_ORIGIN){h.set('Access-Control-Allow-Origin',o);h.set('Access-Control-Allow-Headers','Content-Type, Authorization');h.set('Access-Control-Allow-Methods','GET,POST,OPTIONS')}h.set('Vary','Origin');return new Response(r.body,{status:r.status,headers:h})}
async function login(u,e){const ret=safe(u.searchParams.get('return'),e.SITE_ORIGIN),state=await seal(JSON.stringify({ret,exp:Date.now()+600000}),e.COOKIE_SECRET),g=new URL('https://github.com/login/oauth/authorize');g.searchParams.set('client_id',e.GITHUB_CLIENT_ID);g.searchParams.set('redirect_uri',`${u.origin}/auth/callback`);g.searchParams.set('scope','repo');g.searchParams.set('state',state);return Response.redirect(g,302)}
async function callback(u,e){const s=JSON.parse(await open(u.searchParams.get('state')||'',e.COOKIE_SECRET));if(s.exp<Date.now())throw Error('登录状态已过期');const r=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:e.GITHUB_CLIENT_ID,client_secret:e.GITHUB_CLIENT_SECRET,code:u.searchParams.get('code')})}),x=await r.json();if(!x.access_token)throw Error(x.error_description||'GitHub 登录失败');const session=await seal(x.access_token,e.COOKIE_SECRET),target=new URL(s.ret);target.hash=`session=${encodeURIComponent(session)}`;return Response.redirect(target,302)}
async function status(req,e){const t=await token(req,e);if(!t)return j({authenticated:false});const u=await gh('/user',t);return j({authenticated:u.login===e.ALLOWED_GITHUB_LOGIN,login:u.login})}
async function publish(req,e){const t=await token(req,e);if(!t)return j({error:'请先登录 GitHub'},401);const user=await gh('/user',t);if(user.login!==e.ALLOWED_GITHUB_LOGIN)return j({error:'此账号没有发布权限'},403);const x=await req.json();validate(x);const id=x.id||`note-${Date.now()}`,imgs=[];for(let i=0;i<(x.images||[]).length;i++){const m=/^data:image\/(webp|jpeg|png);base64,(.+)$/.exec(x.images[i]);if(!m)throw Error('图片格式不受支持');const ext=m[1]==='jpeg'?'jpg':m[1],p=`img/notes/${id}/${String(i+1).padStart(2,'0')}.${ext}`;await put(e,p,m[2],`Add image for ${id}`,t);imgs.push(`/${p}`)}const cur=await get(e,'data/notes.json',t),store=JSON.parse(from64(cur.content)),note={id,date:x.date||new Date().toISOString(),title:String(x.title||'').trim(),body:String(x.body||'').trim(),tags:Array.isArray(x.tags)?x.tags.slice(0,8):[],images:imgs};store.version=1;store.updatedAt=new Date().toISOString();store.notes=[note,...(store.notes||[]).filter(n=>n.id!==id)].slice(0,500);await put(e,'data/notes.json',to64(JSON.stringify(store,null,2)+'\n'),`Publish ${id}`,t,cur.sha);return j({ok:true,note})}
function validate(x){if(!x||(!String(x.body||'').trim()&&!(x.images||[]).length))throw Error('至少写一句话或添加一张图片');if(String(x.body||'').length>12000)throw Error('正文过长');if((x.images||[]).length>6)throw Error('最多上传 6 张图片')}
async function token(req,e){const v=req.headers.get('Authorization')?.replace(/^Bearer\s+/,'');if(!v)return null;try{return await open(v,e.COOKIE_SECRET)}catch{return null}}
async function gh(p,t,init={}){const r=await fetch(`https://api.github.com${p}`,{...init,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${t}`,'User-Agent':'mrdream24-notes','X-GitHub-Api-Version':'2022-11-28',...(init.headers||{})}}),x=await r.json();if(!r.ok)throw Error(x.message||`GitHub API ${r.status}`);return x}
function path(e,p){return `/repos/${e.REPO_OWNER}/${e.REPO_NAME}/contents/${p}`}
function get(e,p,t){return gh(`${path(e,p)}?ref=${encodeURIComponent(e.REPO_BRANCH||'master')}`,t)}
function put(e,p,c,m,t,sha){return gh(path(e,p),t,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:m,content:c,branch:e.REPO_BRANCH||'master',...(sha?{sha}:{})})})}
function safe(v,o){try{const u=new URL(v||o,o);return u.origin===o?u.toString():o}catch{return o}}
async function key(s,u){const d=await crypto.subtle.digest('SHA-256',te.encode(s));return crypto.subtle.importKey('raw',d,{name:'AES-GCM'},false,u)}
async function seal(v,s){const iv=crypto.getRandomValues(new Uint8Array(12)),c=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(s,['encrypt']),te.encode(v)));return b64u(new Uint8Array([...iv,...c]))}
async function open(v,s){const b=unb64u(v),iv=b.slice(0,12),d=await crypto.subtle.decrypt({name:'AES-GCM',iv},await key(s,['decrypt']),b.slice(12));return td.decode(d)}
function b64u(b){return btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function unb64u(v){const s=v.replaceAll('-','+').replaceAll('_','/')+'==='.slice((v.length+3)%4);return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function to64(v){return btoa(unescape(encodeURIComponent(v)))}function from64(v){return decodeURIComponent(escape(atob(v.replace(/\n/g,''))))}function j(v,s=200){return new Response(JSON.stringify(v),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
