-- 侦探推理阅读池：个人阅读记录表
-- 在 Supabase Dashboard > SQL Editor 中完整执行本文件。

create table if not exists public.detective_reading_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_id text not null,
  country text not null,
  author_name text not null,
  work_title text not null,
  status text not null check (status in ('want','reading','done','paused')),
  progress smallint not null default 0 check (progress between 0 and 100),
  rating numeric(2,1) check (rating is null or (rating between 1 and 5)),
  started_at date,
  finished_at date,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint detective_reading_records_user_work_unique unique (user_id, work_id)
);

create index if not exists detective_reading_records_user_id_idx
  on public.detective_reading_records(user_id);

create index if not exists detective_reading_records_status_idx
  on public.detective_reading_records(user_id, status);

alter table public.detective_reading_records enable row level security;

-- 每个登录用户只能读取自己的记录。
drop policy if exists "detective records select own" on public.detective_reading_records;
create policy "detective records select own"
on public.detective_reading_records
for select
to authenticated
using (auth.uid() = user_id);

-- 每个登录用户只能写入属于自己的记录。
drop policy if exists "detective records insert own" on public.detective_reading_records;
create policy "detective records insert own"
on public.detective_reading_records
for insert
to authenticated
with check (auth.uid() = user_id);

-- 每个登录用户只能修改自己的记录，并且不能把记录转给其他用户。
drop policy if exists "detective records update own" on public.detective_reading_records;
create policy "detective records update own"
on public.detective_reading_records
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 每个登录用户只能删除自己的记录。
drop policy if exists "detective records delete own" on public.detective_reading_records;
create policy "detective records delete own"
on public.detective_reading_records
for delete
to authenticated
using (auth.uid() = user_id);

-- 自动维护 updated_at，避免其他客户端忘记更新时间。
create or replace function public.set_detective_record_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_detective_record_updated_at on public.detective_reading_records;
create trigger set_detective_record_updated_at
before update on public.detective_reading_records
for each row execute function public.set_detective_record_updated_at();
